-- AlterTable
ALTER TABLE `ExpenseRequest` ADD COLUMN `APPROVED_AT` DATETIME(3) NULL,
    ADD COLUMN `APPROVED_BY` INTEGER NULL,
    ADD COLUMN `COMMENT` VARCHAR(191) NULL;

-- CreateIndex
CREATE INDEX `ExpenseRequest_APPROVED_BY_fkey` ON `ExpenseRequest`(`APPROVED_BY`);

-- AddForeignKey
ALTER TABLE `ExpenseRequest` ADD CONSTRAINT `ExpenseRequest_APPROVED_BY_fkey` FOREIGN KEY (`APPROVED_BY`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
