-- CreateTable
CREATE TABLE `Company` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Role` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Branch` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ID_COMPANY` INTEGER NOT NULL,

    INDEX `Branch_ID_COMPANY_fkey`(`ID_COMPANY`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Area` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ID_BRANCH` INTEGER NOT NULL,

    INDEX `Area_ID_BRANCH_fkey`(`ID_BRANCH`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `EMAIL` VARCHAR(191) NOT NULL,
    `PASSWORD` VARCHAR(191) NOT NULL,
    `ID_COMPANY` INTEGER NULL,
    `ID_BRANCH` INTEGER NULL,
    `ID_AREA` INTEGER NULL,
    `ID_ROLE` INTEGER NOT NULL,
    `MANAGER_ID` INTEGER NULL,

    UNIQUE INDEX `User_EMAIL_key`(`EMAIL`),
    INDEX `User_ID_COMPANY_fkey`(`ID_COMPANY`),
    INDEX `User_ID_BRANCH_fkey`(`ID_BRANCH`),
    INDEX `User_ID_AREA_fkey`(`ID_AREA`),
    INDEX `User_ID_ROLE_fkey`(`ID_ROLE`),
    INDEX `User_MANAGER_ID_fkey`(`MANAGER_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ExpenseRequest` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_USER` INTEGER NOT NULL,
    `MONTO_TOTAL` DOUBLE NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'Pendiente',
    `FECHA` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TRAVEL_REASON` VARCHAR(191) NOT NULL,
    `DEPARTURE_DATE` DATETIME(3) NOT NULL,
    `RETURN_DATE` DATETIME(3) NOT NULL,
    `DISBURSEMENT_DATE` DATETIME(3) NOT NULL,
    `TRAVEL_OBJECTIVES` VARCHAR(191) NOT NULL,
    `APPROVER_ID` INTEGER NULL,
    `COMMENT` VARCHAR(191) NULL,

    INDEX `ExpenseRequest_ID_USER_fkey`(`ID_USER`),
    INDEX `ExpenseRequest_APPROVER_ID_fkey`(`APPROVER_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ExpenseDetail` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_EXPENSE_REQUEST` INTEGER NOT NULL,
    `CONCEPTO` VARCHAR(191) NOT NULL,
    `MONTO` DOUBLE NOT NULL,

    INDEX `ExpenseDetail_ID_EXPENSE_REQUEST_fkey`(`ID_EXPENSE_REQUEST`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Card` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CARD_NUMBER` VARCHAR(191) NOT NULL,
    `ID_USER` INTEGER NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `ASSIGNED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `LIMITE` DECIMAL(65, 30) NOT NULL DEFAULT 0.010000000000000000000000000000,

    UNIQUE INDEX `Card_CARD_NUMBER_key`(`CARD_NUMBER`),
    INDEX `Card_ID_USER_fkey`(`ID_USER`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `InspirationQuote` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CONTENT` VARCHAR(191) NOT NULL,
    `AUTHOR` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Comprobacion` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `viaticoId` VARCHAR(191) NOT NULL,
    `sequence` VARCHAR(191) NOT NULL,
    `dueDate` DATETIME(3) NOT NULL,
    `memo` VARCHAR(191) NOT NULL,
    `debitAmount` DOUBLE NOT NULL,
    `acctName` VARCHAR(191) NOT NULL,
    `ref` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'pendiente',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `userId` INTEGER NOT NULL,
    `expenseRequestId` INTEGER NULL,
    `comprobanteType` VARCHAR(191) NOT NULL DEFAULT 'factura',
    `responsable` VARCHAR(191) NULL,
    `motivo` VARCHAR(191) NULL,
    `descripcion` VARCHAR(191) NULL,
    `importe` DOUBLE NULL,
    `approverId` INTEGER NULL,
    `approverComment` VARCHAR(191) NULL,

    INDEX `Comprobacion_viaticoId_idx`(`viaticoId`),
    INDEX `Comprobacion_userId_idx`(`userId`),
    INDEX `Comprobacion_expenseRequestId_idx`(`expenseRequestId`),
    INDEX `Comprobacion_approverId_idx`(`approverId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Document` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(191) NOT NULL,
    `fileName` VARCHAR(191) NOT NULL,
    `fileContent` LONGBLOB NOT NULL,
    `fileSize` INTEGER NOT NULL,
    `mimeType` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `comprobacionId` INTEGER NOT NULL,
    `description` VARCHAR(191) NULL,

    INDEX `Document_comprobacionId_idx`(`comprobacionId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MovimientosComprobados` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `movimientoSequence` VARCHAR(191) NOT NULL,
    `movimientoDueDate` DATETIME(3) NOT NULL,
    `movimientoRef` VARCHAR(191) NOT NULL,
    `movimientoAcctName` VARCHAR(191) NOT NULL,
    `movimientoDebAmount` DOUBLE NOT NULL,
    `movimientoMemo` VARCHAR(191) NOT NULL,
    `comprobacionId` INTEGER NOT NULL,
    `estado` VARCHAR(191) NOT NULL,
    `fechaComprobacion` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Branch` ADD CONSTRAINT `Branch_ID_COMPANY_fkey` FOREIGN KEY (`ID_COMPANY`) REFERENCES `Company`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Area` ADD CONSTRAINT `Area_ID_BRANCH_fkey` FOREIGN KEY (`ID_BRANCH`) REFERENCES `Branch`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_AREA_fkey` FOREIGN KEY (`ID_AREA`) REFERENCES `Area`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_BRANCH_fkey` FOREIGN KEY (`ID_BRANCH`) REFERENCES `Branch`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_COMPANY_fkey` FOREIGN KEY (`ID_COMPANY`) REFERENCES `Company`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_ROLE_fkey` FOREIGN KEY (`ID_ROLE`) REFERENCES `Role`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_MANAGER_ID_fkey` FOREIGN KEY (`MANAGER_ID`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ExpenseRequest` ADD CONSTRAINT `ExpenseRequest_APPROVER_ID_fkey` FOREIGN KEY (`APPROVER_ID`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ExpenseRequest` ADD CONSTRAINT `ExpenseRequest_ID_USER_fkey` FOREIGN KEY (`ID_USER`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ExpenseDetail` ADD CONSTRAINT `ExpenseDetail_ID_EXPENSE_REQUEST_fkey` FOREIGN KEY (`ID_EXPENSE_REQUEST`) REFERENCES `ExpenseRequest`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Card` ADD CONSTRAINT `Card_ID_USER_fkey` FOREIGN KEY (`ID_USER`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Comprobacion` ADD CONSTRAINT `Comprobacion_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Comprobacion` ADD CONSTRAINT `Comprobacion_expenseRequestId_fkey` FOREIGN KEY (`expenseRequestId`) REFERENCES `ExpenseRequest`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Comprobacion` ADD CONSTRAINT `Comprobacion_approverId_fkey` FOREIGN KEY (`approverId`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Document` ADD CONSTRAINT `Document_comprobacionId_fkey` FOREIGN KEY (`comprobacionId`) REFERENCES `Comprobacion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MovimientosComprobados` ADD CONSTRAINT `MovimientosComprobados_comprobacionId_fkey` FOREIGN KEY (`comprobacionId`) REFERENCES `Comprobacion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
