-- CreateTable
CREATE TABLE `comprobaciones` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `VIATICOS_ID` VARCHAR(191) NOT NULL,
    `SEQUENCE` VARCHAR(191) NOT NULL,
    `DUE_DATE` DATETIME(3) NOT NULL,
    `MEMO` VARCHAR(191) NOT NULL,
    `DEBIT_AMOUNT` DOUBLE NOT NULL,
    `ACCT_NAME` VARCHAR(191) NOT NULL,
    `REF` VARCHAR(191) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'pendiente',
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `USER_ID` INTEGER NOT NULL,
    `EXPENSE_REQUEST_ID` INTEGER NULL,

    INDEX `comprobaciones_VIATICOS_ID_idx`(`VIATICOS_ID`),
    INDEX `comprobaciones_USER_ID_idx`(`USER_ID`),
    INDEX `comprobaciones_EXPENSE_REQUEST_ID_idx`(`EXPENSE_REQUEST_ID`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `comprobaciones` ADD CONSTRAINT `comprobaciones_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `comprobaciones` ADD CONSTRAINT `comprobaciones_EXPENSE_REQUEST_ID_fkey` FOREIGN KEY (`EXPENSE_REQUEST_ID`) REFERENCES `ExpenseRequest`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
