-- AlterTable
ALTER TABLE `Card` ADD COLUMN `ID_COMPANY` INTEGER NULL;

-- CreateIndex
CREATE INDEX `Card_ID_COMPANY_fkey` ON `Card`(`ID_COMPANY`);

-- AddForeignKey
ALTER TABLE `Card` ADD CONSTRAINT `Card_ID_COMPANY_fkey` FOREIGN KEY (`ID_COMPANY`) REFERENCES `Company`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
