-- CreateTable
CREATE TABLE `Company` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Role` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Branch` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ID_COMPANY` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Area` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ID_BRANCH` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `ID_COMPANY` INTEGER NULL,
    `ID_BRANCH` INTEGER NULL,
    `ID_AREA` INTEGER NULL,
    `ID_ROLE` INTEGER NOT NULL,

    UNIQUE INDEX `User_email_key`(`email`),
    INDEX `User_ID_COMPANY_fkey`(`ID_COMPANY`),
    INDEX `User_ID_BRANCH_fkey`(`ID_BRANCH`),
    INDEX `User_ID_AREA_fkey`(`ID_AREA`),
    INDEX `User_ID_ROLE_fkey`(`ID_ROLE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Quotation` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `URL_QUOTATION` VARCHAR(191) NOT NULL,
    `USER_CREATOR` INTEGER NULL,
    `ID_USER` INTEGER NULL,

    INDEX `Quotation_ID_USER_fkey`(`ID_USER`),
    INDEX `Quotation_USER_CREATOR_fkey`(`USER_CREATOR`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ExpenseRequest` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_USER` INTEGER NOT NULL,
    `MONTO_TOTAL` DOUBLE NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'Pendiente',
    `FECHA` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `ExpenseRequest_ID_USER_fkey`(`ID_USER`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ExpenseDetail` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_EXPENSE_REQUEST` INTEGER NOT NULL,
    `CONCEPTO` VARCHAR(191) NOT NULL,
    `MONTO` DOUBLE NOT NULL,

    INDEX `ExpenseDetail_ID_EXPENSE_REQUEST_fkey`(`ID_EXPENSE_REQUEST`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `QuotesUsers` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `QUOTE_ID` INTEGER NULL,
    `ID_USER` INTEGER NULL,

    INDEX `QuotesUsers_ID_USER_fkey`(`ID_USER`),
    INDEX `QuotesUsers_QUOTE_ID_fkey`(`QUOTE_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Branch` ADD CONSTRAINT `Branch_ID_COMPANY_fkey` FOREIGN KEY (`ID_COMPANY`) REFERENCES `Company`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Area` ADD CONSTRAINT `Area_ID_BRANCH_fkey` FOREIGN KEY (`ID_BRANCH`) REFERENCES `Branch`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_COMPANY_fkey` FOREIGN KEY (`ID_COMPANY`) REFERENCES `Company`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_BRANCH_fkey` FOREIGN KEY (`ID_BRANCH`) REFERENCES `Branch`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_AREA_fkey` FOREIGN KEY (`ID_AREA`) REFERENCES `Area`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_ROLE_fkey` FOREIGN KEY (`ID_ROLE`) REFERENCES `Role`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Quotation` ADD CONSTRAINT `Quotation_ID_USER_fkey` FOREIGN KEY (`ID_USER`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Quotation` ADD CONSTRAINT `Quotation_USER_CREATOR_fkey` FOREIGN KEY (`USER_CREATOR`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ExpenseRequest` ADD CONSTRAINT `ExpenseRequest_ID_USER_fkey` FOREIGN KEY (`ID_USER`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ExpenseDetail` ADD CONSTRAINT `ExpenseDetail_ID_EXPENSE_REQUEST_fkey` FOREIGN KEY (`ID_EXPENSE_REQUEST`) REFERENCES `ExpenseRequest`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `QuotesUsers` ADD CONSTRAINT `QuotesUsers_ID_USER_fkey` FOREIGN KEY (`ID_USER`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `QuotesUsers` ADD CONSTRAINT `QuotesUsers_QUOTE_ID_fkey` FOREIGN KEY (`QUOTE_ID`) REFERENCES `Quotation`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
