-- AlterTable
ALTER TABLE `User` ADD COLUMN `MANAGER_ID` INTEGER NULL;

-- CreateIndex
CREATE INDEX `User_MANAGER_ID_fkey` ON `User`(`MANAGER_ID`);

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_MANAGER_ID_fkey` FOREIGN KEY (`MANAGER_ID`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
