-- CreateTable
CREATE TABLE `Card` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CARD_NUMBER` VARCHAR(191) NOT NULL,
    `ID_USER` INTEGER NULL,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT true,
    `ASSIGNED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `Card_CARD_NUMBER_key`(`CARD_NUMBER`),
    INDEX `Card_ID_USER_fkey`(`ID_USER`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Card` ADD CONSTRAINT `Card_ID_USER_fkey` FOREIGN KEY (`ID_USER`) REFERENCES `User`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
