-- AlterTable
ALTER TABLE `comprobaciones` ADD COLUMN `COMPROBANTE_TYPE` VARCHAR(191) NOT NULL DEFAULT 'factura',
    ADD COLUMN `DESCRIPCION` VARCHAR(191) NULL,
    ADD COLUMN `IMPORTE` DOUBLE NULL,
    ADD COLUMN `MOTIVO` VARCHAR(191) NULL,
    ADD COLUMN `RESPONSABLE` VARCHAR(191) NULL;

-- CreateTable
CREATE TABLE `documents` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `TYPE` VARCHAR(191) NOT NULL,
    `FILE_NAME` VARCHAR(191) NOT NULL,
    `FILE_PATH` VARCHAR(191) NOT NULL,
    `FILE_SIZE` INTEGER NOT NULL,
    `MIME_TYPE` VARCHAR(191) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `COMPROBACION_ID` INTEGER NOT NULL,

    INDEX `documents_COMPROBACION_ID_idx`(`COMPROBACION_ID`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `documents` ADD CONSTRAINT `documents_COMPROBACION_ID_fkey` FOREIGN KEY (`COMPROBACION_ID`) REFERENCES `comprobaciones`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
