/*
  Warnings:

  - Added the required column `ID_ROLE` to the `User` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE `User` ADD COLUMN `ID_AREA` INTEGER NULL,
    ADD COLUMN `ID_BRANCH` INTEGER NULL,
    ADD COLUMN `ID_ROLE` INTEGER NOT NULL;

-- CreateTable
CREATE TABLE `Role` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Branch` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ID_COMPANY` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Area` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `ID_BRANCH` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ExpenseRequest` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_USER` INTEGER NOT NULL,
    `MONTO_TOTAL` DOUBLE NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'Pendiente',
    `FECHA` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `ExpenseRequest_ID_USER_fkey`(`ID_USER`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ExpenseDetail` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_EXPENSE_REQUEST` INTEGER NOT NULL,
    `CONCEPTO` VARCHAR(191) NOT NULL,
    `MONTO` DOUBLE NOT NULL,

    INDEX `ExpenseDetail_ID_EXPENSE_REQUEST_fkey`(`ID_EXPENSE_REQUEST`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `User_ID_BRANCH_fkey` ON `User`(`ID_BRANCH`);

-- CreateIndex
CREATE INDEX `User_ID_AREA_fkey` ON `User`(`ID_AREA`);

-- CreateIndex
CREATE INDEX `User_ID_ROLE_fkey` ON `User`(`ID_ROLE`);

-- AddForeignKey
ALTER TABLE `Branch` ADD CONSTRAINT `Branch_ID_COMPANY_fkey` FOREIGN KEY (`ID_COMPANY`) REFERENCES `Company`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Area` ADD CONSTRAINT `Area_ID_BRANCH_fkey` FOREIGN KEY (`ID_BRANCH`) REFERENCES `Branch`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_BRANCH_fkey` FOREIGN KEY (`ID_BRANCH`) REFERENCES `Branch`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_AREA_fkey` FOREIGN KEY (`ID_AREA`) REFERENCES `Area`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_ID_ROLE_fkey` FOREIGN KEY (`ID_ROLE`) REFERENCES `Role`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ExpenseRequest` ADD CONSTRAINT `ExpenseRequest_ID_USER_fkey` FOREIGN KEY (`ID_USER`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ExpenseDetail` ADD CONSTRAINT `ExpenseDetail_ID_EXPENSE_REQUEST_fkey` FOREIGN KEY (`ID_EXPENSE_REQUEST`) REFERENCES `ExpenseRequest`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
